#### Code 1: Installing Extension **nbextension** - variable inspector
• **nbextension** - variable inspector<br>

In [23]:
#download and install add-on for jupyter
!pip install jupyter_contrib_nbextensions
#run first time to enable
jupyter contrib nbextension install --user
#enable exact extension inside nbextension add-on

SyntaxError: invalid syntax (<ipython-input-23-76f338b2aa2b>, line 4)

#### Code 2: 
•<br>

In [5]:
import numpy as np
import pandas as pd
x = 55
long_string = "This is a very long string with many words in it"

In [12]:
a = np.random.rand(100, 100)
data = pd.DataFrame(a)
print(a, data)

[[0.74796963 0.22610478 0.34482175 ... 0.98506036 0.42513216 0.14294842]
 [0.4419419  0.00330898 0.16266355 ... 0.65177382 0.99743067 0.96915837]
 [0.20965088 0.53934107 0.28172079 ... 0.61023344 0.31188624 0.83766026]
 ...
 [0.13396667 0.95223947 0.13216431 ... 0.17702046 0.07500191 0.21519672]
 [0.14705787 0.80018464 0.33958829 ... 0.95084631 0.13241479 0.89864722]
 [0.85341687 0.14273325 0.44156131 ... 0.04204846 0.92430002 0.5078282 ]]           0         1         2         3         4         5         6   \
0   0.747970  0.226105  0.344822  0.462346  0.070506  0.455413  0.018834   
1   0.441942  0.003309  0.162664  0.701162  0.302258  0.802280  0.615619   
2   0.209651  0.539341  0.281721  0.640766  0.226426  0.276345  0.194078   
3   0.161176  0.001990  0.349593  0.902949  0.441543  0.191923  0.173999   
4   0.091110  0.518517  0.314230  0.611638  0.932156  0.289568  0.970512   
5   0.904678  0.202112  0.446797  0.368870  0.885290  0.236514  0.196570   
6   0.725568  0.388235  

#### Code 4:  How To Define My Own Function
•*docstrings are documentation strings documenting functions inside of a function*<br>

In [21]:
#Definition/Function/Method(only if the function is in a class)
def print_battlecry():
    print("Lok´Tar-Ogar")
"""docstring definition of this function"""

#Calling of the Function    
print(print_battlecry())
print_battlecry()

Lok´Tar-Ogar
None
Lok´Tar-Ogar


#### Code 5: + Print Obvod Trojuholnika
• Black-Box Symbolic - Know Your Expected Output and Expected Inputs
• We always get from function only one(actual) output.<br>
• In function´s definition we put an expected inputs into ***()*** of function as *parameters* <br>
• When we call the function, we need to input required data into ***()*** as *positional arguments* <br>
• ***print()*** ´s output format = `<empty>`: output <br>

In [40]:
#def - parameters a, b, c
def vypocitaj_obvod(a, b, c):
    print("Obvod trojuholnika je: ", a+b+c)

#call - arguments a, b, c
vypocitaj_obvod(1,2,3)

Obvod trojuholnika je:  6


#### Code 6a: Out Full User Name<a id='01'> (dependency of 6b)</a> 
• A good practice in python is to use short names for function parameters.<br>
• A python string method ***strip()*** remove spaces at the beginning and at the end of the string.<br>
• ***return*** ´s output format = `<Out>`: output  -return does not output anything in general <br>
    

In [66]:
def vypis_cele_meno(m, p):
    """Funkcia na vypis celeho mena pouzivatela, prve pismena velke, s osetrenim medzier
        m = meno 
        p = priezvisko
    """
    cele_meno = m.strip() + " " + p.strip()
    cele_meno = cele_meno.title()
#output
    return cele_meno
#call

"""Example of messed up spaces because of importing from file or database:"""
Gregor = "           marek  "
Krab = "   rybanský        "

vypis_cele_meno(Gregor, Krab)
#If we add:
#    print("Cele meno je: ",vypis_cele_meno(Krab, Gregor))
#Then the Out[num]: will change to print´s output

'Marek Rybanský'

#### Code 6b:Print Full User Name + Orientation in Documentation of Function- (dependencies: [6a](#01))

In [71]:
print("Cele meno je: ",vypis_cele_meno(Krab, Gregor))

print(vypis_cele_meno.__doc__)

Cele meno je:  Rybanský Marek
Funkcia na vypis celeho mena pouzivatela, prve pismena velke, s osetrenim medzier
        m = meno 
        p = priezvisko
    


#### Code 7: 

In [78]:
string = "s"
string.strip().__doc__

"str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."

#### Code 9: Module ***getpass*** - get username

In [19]:
#!pip install getpass --if module nto found
import getpass
import os

#get logged user
print(getpass.getuser())

## alternative
#do not always work well under linux - it is trying to get logged user info through world environments
print(os.getlogin())
print(os.environ.get("USERNAME"))
print(os.environ.get("USER", os.environ.get("USERNAME")))

print(os.environ.get("USER"))

pc
pc
pc
pc
None


#### Code 10 Module ***getpass***  - hide password when typing(simple login prompt)
• In Python version 3 and up input works with strings

In [24]:
from getpass import getpass as gp
pouzivatel_meno = input("Zadajte meno pouzivatela: ")
heslo = gp("Zadajte heslo: ")

print(f"Vase Meno je: {pouzivatel_meno}, a Heslo: {heslo}")

Zadajte meno pouzivatela: admin
Zadajte heslo: ········
Vase Meno je: admin, a Heslo: titan
